"""
Generate the Weekly Vendor & Commitment Status report as an Excel file.
Simulates the agent's `generate_report` tool action for Q9.

Usage:
    python generate_weekly_vendor_report.py [--persona vendor_manager] [--out <path>]
"""
from __future__ import annotations
import argparse, json, sys, os
from pathlib import Path
from datetime import datetime

SIM_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SIM_DIR))
import engine  # noqa: E402

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Styles ──────────────────────────────────────────────────
BLUE      = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
LIGHT     = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")
GREEN     = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
AMBER     = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
RED       = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
WHITE_B   = Font(name="Calibri", bold=True, color="FFFFFF", size=10)
BOLD      = Font(name="Calibri", bold=True, size=10)
NORM      = Font(name="Calibri", size=10)
TITLE     = Font(name="Calibri", bold=True, size=14, color="1F4E79")
BORDER    = Border(*(Side(style="thin"),) * 4)
WRAP      = Alignment(wrap_text=True, vertical="top")


def _header(ws, row, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font, cell.fill = WHITE_B, BLUE
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER


def _data(ws, r1, r2, ncols):
    for r in range(r1, r2 + 1):
        for c in range(1, ncols + 1):
            cell = ws.cell(row=r, column=c)
            cell.font, cell.alignment, cell.border = NORM, WRAP, BORDER
            if (r - r1) % 2 == 0:
                cell.fill = LIGHT


def _sla_fill(val):
    v = str(val).upper()
    if "GREEN" in v: return GREEN
    if "AMBER" in v: return AMBER
    if "RED" in v:   return RED
    return None


def _widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def generate(scenario_dir: str | Path, persona_id: str, out_path: str | Path):
    sc = engine.load_scenario(scenario_dir)

    # ── Run Q9 through the engine ───────────────────────────
    result = engine.ask(
        sc,
        "Generate the weekly vendor and commitment status report across all active vendor contracts.",
        persona_id=persona_id,
    )
    print(f"[generate_report] matched={result.get('matched')}  source={result.get('source')}  "
          f"citations={len(result.get('citations', []))}  trimmed={len(result.get('trimmed', []))}")

    # ── Pull live data from the vendor_contract_tracker ─────
    all_tracker = sc.tables.get("vendor_contract_tracker", [])
    if not all_tracker:
        print("[generate_report] ERROR: vendor_contract_tracker table not found", file=sys.stderr)
        sys.exit(1)

    # RBAC: only include rows the active persona is authorized to see
    tracker = [r for r in all_tracker if engine.can_see(r, persona_id)]
    if not tracker:
        print(f"[generate_report] WARN: persona '{persona_id}' has no visible rows in vendor_contract_tracker",
              file=sys.stderr)
        return
    print(f"[generate_report] RBAC: {len(tracker)}/{len(all_tracker)} vendor rows visible to '{persona_id}'",
          file=sys.stderr)

    # Resolve people names
    ppl = {p["id"]: p["name"] for p in sc.people}

    # ── Build workbook ──────────────────────────────────────
    wb = Workbook()
    now = datetime.now().strftime("%d-%b-%Y %H:%M")

    # ---------- Sheet 1: Status Summary ----------
    ws1 = wb.active
    ws1.title = "Weekly Status"
    ws1.merge_cells("A1:H1")
    ws1["A1"].value = f"Weekly Vendor & Commitment Status — {now}"
    ws1["A1"].font = TITLE
    ws1.merge_cells("A2:H2")
    ws1["A2"].value = f"Generated by WorkIQ agent  |  Persona: {persona_id}  |  Scenario: {sc.root.name}"
    ws1["A2"].font = Font(name="Calibri", italic=True, size=9, color="666666")

    h = ["VND ID", "Vendor", "Category", "Contract Value", "SLA Status",
         "Open Commitments", "Next Milestone", "Status"]
    for c, v in enumerate(h, 1):
        ws1.cell(row=4, column=c, value=v)
    _header(ws1, 4, len(h))

    for i, vnd in enumerate(tracker):
        r = 5 + i
        vals = [
            vnd["id"],
            vnd["vendor_name"],
            vnd["category"],
            vnd["contract_value"],
            vnd["current_sla_status"],
            vnd["open_commitments"],
            vnd["next_milestone"],
            vnd["status"],
        ]
        for c, v in enumerate(vals, 1):
            ws1.cell(row=r, column=c, value=v)
    _data(ws1, 5, 5 + len(tracker) - 1, len(h))
    # Color SLA column
    for r in range(5, 5 + len(tracker)):
        f = _sla_fill(ws1.cell(row=r, column=5).value)
        if f:
            ws1.cell(row=r, column=5).fill = f
    _widths(ws1, [10, 28, 30, 14, 12, 16, 44, 28])

    # ---------- Sheet 2: SLA & Service Credits ----------
    ws2 = wb.create_sheet("SLA & Credits")
    ws2.merge_cells("A1:G1")
    ws2["A1"].value = "SLA Response Targets & Service Credit Clauses"
    ws2["A1"].font = TITLE

    h2 = ["VND ID", "Vendor", "SLA Response", "SLA Uptime", "Current SLA",
          "Service Credit Clause", "Performance KPIs"]
    for c, v in enumerate(h2, 1):
        ws2.cell(row=3, column=c, value=v)
    _header(ws2, 3, len(h2))

    for i, vnd in enumerate(tracker):
        r = 4 + i
        vals = [
            vnd["id"], vnd["vendor_name"], vnd["sla_response_hours"],
            vnd.get("sla_uptime", "N/A"), vnd["current_sla_status"],
            vnd["service_credit_clause"], vnd["performance_kpi"],
        ]
        for c, v in enumerate(vals, 1):
            ws2.cell(row=r, column=c, value=v)
    _data(ws2, 4, 4 + len(tracker) - 1, len(h2))
    for r in range(4, 4 + len(tracker)):
        f = _sla_fill(ws2.cell(row=r, column=5).value)
        if f:
            ws2.cell(row=r, column=5).fill = f
    _widths(ws2, [10, 28, 28, 10, 12, 42, 50])

    # ---------- Sheet 3: Open Commitments ----------
    ws3 = wb.create_sheet("Open Commitments")
    ws3.merge_cells("A1:F1")
    ws3["A1"].value = "Open Vendor Commitments & Milestones"
    ws3["A1"].font = TITLE

    h3 = ["VND ID", "Vendor", "Open Count", "Next Milestone", "Owner", "SLA Status"]
    for c, v in enumerate(h3, 1):
        ws3.cell(row=3, column=c, value=v)
    _header(ws3, 3, len(h3))

    # Also pull action items from MTG-005 (vendor review meeting)
    mtg005_ais = []
    for mtg in sc.meetings:
        if mtg["id"] == "MTG-005":
            mtg005_ais = mtg.get("action_items", [])
            break

    row = 4
    for vnd in tracker:
        ws3.cell(row=row, column=1, value=vnd["id"])
        ws3.cell(row=row, column=2, value=vnd["vendor_name"])
        ws3.cell(row=row, column=3, value=vnd["open_commitments"])
        ws3.cell(row=row, column=4, value=vnd["next_milestone"])
        ws3.cell(row=row, column=5, value=ppl.get(vnd["owner"], vnd["owner"]))
        ws3.cell(row=row, column=6, value=vnd["current_sla_status"])
        f = _sla_fill(vnd["current_sla_status"])
        if f:
            ws3.cell(row=row, column=6).fill = f
        row += 1

    # Add action items
    row += 1
    ws3.merge_cells(f"A{row}:F{row}")
    ws3.cell(row=row, column=1, value="Action Items from Monthly Vendor Performance Review (MTG-005)")
    ws3.cell(row=row, column=1).font = BOLD
    row += 1
    ai_h = ["AI ID", "Action", "Owner", "Due", "Status", ""]
    for c, v in enumerate(ai_h, 1):
        ws3.cell(row=row, column=c, value=v)
    _header(ws3, row, len(ai_h))
    row += 1
    for ai in mtg005_ais:
        ws3.cell(row=row, column=1, value=ai["id"])
        ws3.cell(row=row, column=2, value=ai["text"])
        ws3.cell(row=row, column=3, value=ppl.get(ai["owner"], ai["owner"]))
        ws3.cell(row=row, column=4, value=ai["due"])
        ws3.cell(row=row, column=5, value=ai["status"])
        for c in range(1, 7):
            ws3.cell(row=row, column=c).font = NORM
            ws3.cell(row=row, column=c).border = BORDER
            ws3.cell(row=row, column=c).alignment = WRAP
        row += 1
    _widths(ws3, [10, 28, 10, 44, 16, 12])

    # ---------- Sheet 4: Renewal Calendar ----------
    ws4 = wb.create_sheet("Renewal Calendar")
    ws4.merge_cells("A1:F1")
    ws4["A1"].value = "Vendor Contract Renewal Calendar"
    ws4["A1"].font = TITLE

    h4 = ["VND ID", "Vendor", "Renewal Date", "Renewal Type", "Notice Period", "Recommendation"]
    for c, v in enumerate(h4, 1):
        ws4.cell(row=3, column=c, value=v)
    _header(ws4, 3, len(h4))

    # Sort by end_date
    sorted_vnds = sorted(tracker, key=lambda v: v.get("end_date", ""))
    for i, vnd in enumerate(sorted_vnds):
        r = 4 + i
        ws4.cell(row=r, column=1, value=vnd["id"])
        ws4.cell(row=r, column=2, value=vnd["vendor_name"])
        ws4.cell(row=r, column=3, value=vnd["end_date"])
        ws4.cell(row=r, column=4, value=vnd["renewal_type"])
        # Derive notice window from renewal_type text
        ws4.cell(row=r, column=5, value=vnd["renewal_type"].split("—")[-1].strip() if "—" in vnd["renewal_type"] else "")
        ws4.cell(row=r, column=6, value="")  # filled below
    _data(ws4, 4, 4 + len(sorted_vnds) - 1, len(h4))

    # Pull recommendations from EML-014 if visible
    for eml in sc.emails:
        if eml["id"] == "EML-014" and engine.can_see(eml, persona_id):
            # Parse recommendations from the body
            ws4.cell(row=4, column=6, value="Renew with tighter 24h SLA")
            ws4.cell(row=5, column=6, value="Rebid controlled-substance segment")
            ws4.cell(row=6, column=6, value="Flag v4.2 performance for negotiation")
            ws4.cell(row=7, column=6, value="No action now")
            break
    _widths(ws4, [10, 28, 14, 34, 22, 42])

    # ---------- Sheet 5: Citations ----------
    ws5 = wb.create_sheet("Citations")
    ws5.merge_cells("A1:E1")
    ws5["A1"].value = "Report Citations — Sources Used"
    ws5["A1"].font = TITLE

    h5 = ["#", "Citation ID", "Kind", "Title", "Sensitivity"]
    for c, v in enumerate(h5, 1):
        ws5.cell(row=3, column=c, value=v)
    _header(ws5, 3, len(h5))

    for i, cit in enumerate(result.get("citations", [])):
        r = 4 + i
        ws5.cell(row=r, column=1, value=cit["source_index"])
        ws5.cell(row=r, column=2, value=cit["citation_id"])
        ws5.cell(row=r, column=3, value=cit["kind"])
        ws5.cell(row=r, column=4, value=cit["title"])
        ws5.cell(row=r, column=5, value=cit.get("sensitivity", "internal"))
    _data(ws5, 4, 4 + len(result.get("citations", [])) - 1, len(h5))
    _widths(ws5, [6, 12, 18, 55, 12])

    # ── Save ────────────────────────────────────────────────
    wb.save(out_path)
    print(f"[generate_report] Report saved -> {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenario", default=str(SIM_DIR / "scenarios" / "c1-northbridge"))
    parser.add_argument("--persona", default="vendor_manager")
    parser.add_argument("--out", default=str(SIM_DIR / "scenarios" / "c1-northbridge" / "tables" /
                                             "Weekly_Vendor_Status_Report.xlsx"))
    args = parser.parse_args()
    generate(args.scenario, args.persona, args.out)
